# Generated by Django 6.0.2 on 2026-04-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockcannon',
            name='features',
        ),
        migrations.RemoveField(
            model_name='transitstop',
            name='rock_cannon',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='TransitStop',
        ),
    ]
